#:import dp kivy.metrics.dp
#:include 'kivymd/book_card_view.kv'
#:import get_color_from_hex kivy.utils.get_color_from_hex

<Home>:
    name: 'book_list'
    id: book_list_screen
    md_bg_color: app.theme_cls.surfaceColor

    MDBoxLayout:
        id: boxlayout
        orientation: 'vertical'
        size_hint: 1, 1
        padding: '5dp'
        spacing: '15dp'

        MDBoxLayout:
            size_hint: 1, 0.15
            spacing: '10dp'
            pos_hint: {'top': 1}
            MDTextField:
                id: search_text
                size_hint_x: 0.8
                adaptive_height: True
                on_text: root.search(search_text.text)
                
                MDTextFieldLeadingIcon:
                    icon: 'magnify'
                MDTextFieldHintText:
                    text: 'Search books'
            
            MDButton:
                radius: [dp(7),dp(7),dp(7),dp(7)]
                theme_bg_color: 'Custom'
                md_bg_color: 'blue'
                on_release: root.open_options(self)

                MDButtonIcon:
                    icon: 'arrow-bottom-left-bold-outline'
                MDButtonText:
                    id: option_button_text
                    text: 'Book no.'

        MDLabel:
            size_hint: 1, None
            height: '50dp'
            text: root.total
            padding: '15dp'
            canvas.before:
                Color:
                    rgba: get_color_from_hex("#4AA3DF")
                Rectangle:
                    size: self.size
                    pos: self.pos
        MDRecycleView:
            id: rv
            viewclass: 'BookCardView' 
            data: root.book_data
            scroll_wheel_distance: '30dp'
            smooth_scroll_end: 10

            MDRecycleGridLayout:
                padding: dp(10)
                spacing: dp(15)
                cols: max(1, int(self.width / (dp(150) + dp(10) + dp(15))))
                size_hint_y: None
                height: self.minimum_height
                default_size_hint: None, None
                default_height: "250dp"
                default_width: "150dp"
        
    #size_hint: None, None
    #size: '150dp', '250dp'