<BookDetailDialog>
    background: ''
    md_bg_color: 0.1,0.1,0.1,0.75
    MDDialogHeadlineText:
        text: root.book_dict['title']
        halign: 'left'
        valign:'bottom'

    MDDialogContentContainer:
        size_hint_y: None
        height: '250dp'
        MDScrollView:
            do_scroll_x: False
            scroll_wheel_distance: '30dp'
            smooth_scroll_end: 10
            bar_width: '3dp'
            bar_inactive_color: 0, 0, 0, 1

            MDBoxLayout:
                id: info_box
                orientation: 'vertical'
                height: self.minimum_height
                size_hint_y: None
                #spacing: '10dp'


    MDDialogButtonContainer:
        size_hint_x: None
        width: '500dp'
        spacing: '15dp'
        Widget:
            size_hint_x: 0.8

        MDButton:
            adaptive_size: True
            on_release: root.move_to_edit()
            MDButtonText:
                text: 'Edit'

            MDButtonIcon:
                icon: 'database-edit'
        
        MDButton:
            adaptive_size: True
            on_release: root.move_to_issue()
            MDButtonText:
                text: 'Issue'
        
        MDButton:
            adaptive_size: True
            style: 'text'
            on_release: root.dismiss()
            MDButtonText:
                text: 'Close'

