#:import get_color_from_hex kivy.utils.get_color_from_hex

<CustomLabel@MDLabel>:
    theme_text_color: 'Custom'
    text_color: 1,1,1

<BookCardView>
    id: book_card_view
    theme_shadow_offset: "Custom"
    theme_shadow_softness: "Custom"
    orientation: 'vertical'
    ripple_behavior: True
    theme_bg_color: 'Custom'
    md_bg_color: app.theme_cls.transparentColor
    shadow_softness: 1
    shadow_offset: (1, -2)
    theme_shadow_color: 'Custom'
    shadow_color: 'green'
    size_hint: None, None
    size: '150dp', '250dp'
    spacing: '5dp'
    padding: '5dp'
    theme_elevation_level: "Custom"
    elevation_level: 5
    style: 'elevated'

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  # Standard white color for the texture
        RoundedRectangle:
            size: self.size
            pos: self.pos
            source: 'assets/img/book-card-bg.png'
            radius: [10, 10, 10, 10]

        Color:
            # Applying a semi-transparent black overlay (e.g., 20% opacity)
            # This subtly darkens the background image for better text contrast
            rgba: 0, 0, 0, 0.50 
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10, 10, 10, 10]

    Image:
        source: 'assets/img/book-card-icon.png'
        size_hint: 1, 0.5
    
    CustomLabel:
        text: root.text
        markup: True
        size_hint: 1, 0.2
    
    CustomLabel:
        text: root.status
        size_hint: 1, 0.2
        theme_text_color: 'Custom'
        text_color: 'red' if root.status=='Unavailable' else 'green'
