<ErrorBar>
    size_hint_x: 0.5
    pos_hint: {"center_x": 0.5}
    size_hint_y: None
    on_open: root.play_sound()
    y: dp(48)

    MDSnackbarText:
        text: 'Error'
    
    MDSnackbarSupportingText:
        text: root.text
        padding: [0, 0, 0, dp(56)]
        theme_text_color: 'Custom'
        text_color: 'crimson'
    
    MDSnackbarButtonContainer:
        MDSnackbarActionButton:
            on_release: root.open_help()
            MDSnackbarActionButtonText:
                text: 'help'
        
        MDSnackbarCloseButton:
            icon: 'close'
            on_release: root.dismiss()
    