<MDIconLabel1@MDBoxLayout>
    MDRelativeLayout:
        size_hint: 0.4,1
        MDIcon:
            icon: 'book-arrow-up'
            pos_hint: {'center_x': 0.9, 'center_y':0.55}

    MDLabel:
        size_hint: 0.6,1
        text: 'Issue Books'
        halign: 'left'
        theme_font_size: 'Custom'
        font_size: '24sp'


<ITextField@MDTextField>
    mode: 'filled'
    on_text_validate: root.parent.parent.parent.move_next(self)

<IssueBooks>:
    MDScrollView:
        do_scroll_x: False
        size_hint: 1, 0.9
        pos_hint: {'top':0.9}
        scroll_wheel_distance: '30dp'
        smooth_scroll_end: 10
        bar_width: '5dp'
        bar_inactive_color: 0, 0, 0, 1
        
        MDBoxLayout:
            orientation: 'vertical'
            spacing: '20dp'
            padding: '15dp'
            adaptive_height: True
            
            MDLabel:
                text: "Issue Book"
                theme_font_style: 'Custom'
                font_style: 'Display'
                role: 'small'
                halign: 'left'
                size_hint: 1, None
                height: dp(10)
                        
        
            MDDivider: #Fix this divider color
                theme_divider_color: 'Custom'
                color: self.theme_cls.primaryColor

            ITextField:
                id: book_no
                on_text: root.search_book(self)
                hint_text: 'Book No.'
                required: True
                MDTextFieldHintText:
                    text: 'Book No.'
                
                MDTextFieldHelperText:
                    text: '*Required'
                    mode: 'on_error'

            ITextField:
                id: book_name
                hint_text: 'Title'
                MDTextFieldHintText:
                    text: 'Title'
            ITextField:
                id: author
                hint_text: 'Author'
                MDTextFieldHintText:
                    text: 'Author'
            ITextField:
                id: category
                hint_text: 'Category'
                MDTextFieldHintText:
                    text: 'Category'
            
            MDDivider:
            
            ITextField:
                id: cadet_no
                hint_text: 'Cadet No.'
                on_text: root.search(cadet_no)
                required: True
                MDTextFieldHintText:
                    text: 'Cadet No.'
                
                MDTextFieldHelperText:
                    text: '*Required'
                    mode: 'on_error'
                
            MDLabel:
                text: root.issue_cadet_name
                size_hint_y: None
                height: self.texture_size[1] + dp(15)
            
            MDLabel:
                text: root.issue_cadet_batch
                size_hint_y: None
                height: self.texture_size[1] + dp(15)
            
            MDButton:
                style: 'tonal'
                pos_hint: {'center_x': 0.5}
                on_press: root.issue_book()
                MDButtonText:
                    text: 'Issue'
            

