<MyList>
    id: my_list
    on_press: root.show_details()
    MDListItemHeadlineText:
        text: root.book_name
    MDListItemSupportingText:
        text: root.book_no
    
    MDListItemTertiaryText:
        text: root.cadet_name
    

<IssueList>:
    MDBoxLayout:
        orientation: 'vertical'

        MDBoxLayout:
            size_hint: 1, 0.15
            spacing: '15dp'

            MDTextField:
                id: itext
                size_hint_x: 0.8
                adaptive_width: True
                on_text: root.search(itext.text)

                MDTextFieldHintText:
                    text: 'Search'
                MDTextFieldLeadingIcon:
                    icon: 'magnify'
            
            MDButton:
                size_hint_x: 0.2
                adaptive_width: True
                on_release: root.open_options(self)
                id: search_plate
                
                MDButtonText:
                    text: 'Cadet no'
                
                MDButtonIcon:
                    icon: 'arrow-bottom-left-bold-outline'

        RecycleView:
            id: rv
            viewclass: 'MyList'     # make sure it knows what class to render
            data: root.issue_data

            RecycleBoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                default_size_hint: 1, None
                default_height: "80dp"   # enough height for list items
        