<NotificationBar>
    size_hint_x: 0.5
    pos_hint: {"center_x": 0.5}
    size_hint_y: None
    on_open: root.play_sound()
    y: dp(48)

    MDSnackbarSupportingText:
        text: root.text
        theme_text_color: 'Custom'
        text_color: root.color
        padding: [0, 0, 0, dp(56)]
    
    MDSnackbarButtonContainer:
        MDSnackbarActionButton:
            on_release: root.action()
            MDSnackbarActionButtonText:
                text: root.button_text
    