<MDIconLabel2@MDBoxLayout>
    MDRelativeLayout:
        size_hint: 0.4,1
        MDIcon:
            icon: 'account-plus'
            pos_hint: {'center_x': 0.9, 'center_y':0.55}

    MDLabel:
        size_hint: 0.6,1
        text: 'Register User'
        halign: 'left'
        theme_font_size: 'Custom'
        font_size: '24sp'

<Register>:
    md_bg_color: self.theme_cls.backgroundColor
    MDBoxLayout:
        size_hint: 0.5,0.5
        pos_hint: {'center_x':0.5, 'center_y':0.55}
        orientation: 'vertical'
        spacing: '20dp'

        MDIconLabel2:
            pos_hint: {'center_x':0.5}
        MDTextField:
            id: name_register
            MDTextFieldHintText:
                text: 'Cadet Name'
        
        MDTextField:
            id: cadet_no_register
            MDTextFieldMaxLengthText:
                max_text_length: 4
            MDTextFieldHintText:
                text: 'Cadet No.'
        
        MDTextField:
            id: batch_register
            MDTextFieldHintText:
                text: 'Batch'
            
            MDTextFieldHelperText:
                text: 'Integers only'
                mode: 'on_error'
        
        MDButton:
            size_hint: None, None
            size: 110, 50
            pos_hint: {'center_x':0.5}
            on_press: root.register_user()
            MDButtonText:
                text: 'Register'
            

