#:import get_color_from_hex kivy.utils.get_color_from_hex
<UserList>
    id: user_list
    on_press: root.show_details()
    theme_bg_color: 'Custom'
    #md_bg_color: root.convert_rgba(root.color, alpha=0.5)
    
    MDListItemLeadingAvatar:
        source: root.icon
    MDListItemHeadlineText:
        text: root.name
    MDListItemSupportingText:
        text: root.cadet_no
    
    MDListItemTertiaryText:
        text: f'{root.batch} batch'
    
    MDListItemTrailingSupportingText:
        text: root.role
        theme_text_color: 'Custom'
        color: root.convert_rgba(root.color)


<Users>:
    MDBoxLayout:
        orientation: 'vertical'
        padding: '15dp'
        spacing: '10dp'
        MDBoxLayout:
            size_hint: 1, 0.15
            spacing: '15dp'

            MDTextField:
                id: utext
                size_hint_x: 0.8
                adaptive_width: True
                on_text: root.search(utext.text)

                MDTextFieldHintText:
                    text: 'Search'
                MDTextFieldLeadingIcon:
                    icon: 'magnify'
            
            MDButton:
                size_hint_x: 0.2
                adaptive_width: True
                on_release: root.open_options(self)
                
                MDButtonText:
                    id: search_plate
                    text: 'Cadet name'
                
                MDButtonIcon:
                    icon: 'arrow-bottom-left-bold-outline'
        
        MDLabel:
            text: f'Total: {root.total}'
            size_hint_y: None
            height: '50dp'
            padding: '10dp'
            canvas.before:
                Color:
                    rgba: get_color_from_hex("#4AA3DF")
                Rectangle:
                    size: self.size
                    pos: self.pos


        RecycleView:
            id: rv
            viewclass: 'UserList'
            data: root.user_data
            scroll_wheel_distance: '30dp'
            smooth_scroll_end: 10

            RecycleBoxLayout:
                padding: ['0dp', '10dp']
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                default_size_hint: 1, None
                default_height: "80dp"